name: Build gfootball on Mac

on:
  push:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15, macos-latest ]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Check out football repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install brew dependencies
        run: brew install cmake sdl2 sdl2_image sdl2_ttf sdl2_gfx boost

      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel build psutil
          python3 -m pip install -r requirements.txt

      - name: Build package
        run: python3 -m build --no-isolation --wheel
