name: Build gfootball on Mac

on:
  push:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]  # [ macos-10.15, macos-latest ]
        # TODO: Test with different Python versions, e.g. python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Check out football repository
        uses: actions/checkout@v2

      - name: Install brew dependencies
        run: |
          brew install python3 cmake sdl2 sdl2_image sdl2_ttf sdl2_gfx boost boost-python3

      - name: Upgrade pip and essential dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel build psutil

      - name: Build package
        run: python3 -m build --wheel

