# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Wheels

on: push
#   release:
#     types: [published]

jobs:
  deploy:
    
    runs-on: windows-latest
    
    env:
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg-py3.9    
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: football

#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.9'
#    - name: Upgrade pip and essential dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install build setuptools psutil wheel

    - name:  Restore vcpkg libs from cache
      id: cache-vcpkg
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.VCPKG_ROOT }}/installed
          ${{ env.VCPKG_ROOT }}/scripts
        key: ${{ runner.os }}-py3.9-alpha  # -${{ hashFiles('CMakeLists.txt') }}
    - name: Checkout vcpkg if cache failed
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: microsoft/vcpkg
        path: vcpkg-py3.9  #vcpkg-py{{python-version}}

    - name: Show content of workspace after cache has been restored
      run: find $RUNNER_WORKSPACE
      shell: bash
      
    - name: Bootstrap vcpkg and install packages if cache failed
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        ${{ env.VCPKG_ROOT }}\bootstrap-vcpkg.bat
        ${{ env.VCPKG_ROOT }}\vcpkg.exe install --triplet x64-windows boost-thread boost-filesystem boost-python sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-gfx opengl
        ${{ env.VCPKG_ROOT }}\vcpkg.exe install --triplet x86-windows boost-thread boost-filesystem boost-python sdl2 sdl2-image[libjpeg-turbo] sdl2-ttf sdl2-gfx opengl

    - name: Show content of workspace after packages have been installed
      run: find $RUNNER_WORKSPACE
      shell: bash
    # ...
      
#    - name: Run pip install
#      run: |
#        cd football
#        python -m pip install . --use-feature=in-tree-build

#     - name: Build package
#       run: python -m build
#     - name: Publish package
#       uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#       with:
#         user: __token__
#         password: ${{ secrets.PYPI_API_TOKEN }}
